"use client";
import { useMemo, useState } from "react";
import { Eye, FileText, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { money } from "@/lib/format";

type Product = any;
type Order = any;

const emptyProduct = { name:"", type:"Men's Stainless Steel", regularPrice:0, salePrice:0, costPrice:0, discount:0, stock:0, images:"", features:"", longDescription:"", movement:"Japanese Quartz", strap:"Stainless Steel", waterResistance:"30M" };

export default function AdminClient({initial}:{initial:any}) {
  const [d,setD]=useState(initial);
  const [search,setSearch]=useState("");
  const [selectedOrder,setSelectedOrder]=useState<Order|null>(null);
  const [selectedProduct,setSelectedProduct]=useState<Product|null>(null);
  const [productForm,setProductForm]=useState<any>(emptyProduct);
  const [productOpen,setProductOpen]=useState(false);
  const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState("");
  const router=useRouter();

  const products=useMemo(()=>d.products.filter((p:any)=>p.name.toLowerCase().includes(search.toLowerCase())||p.type.toLowerCase().includes(search.toLowerCase())),[d.products,search]);
  const refresh=()=>router.refresh();
  async function stock(id:string,stock:number){await fetch(`/api/admin/products/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({stock})});refresh();}
  async function status(id:string,status:string){const r=await fetch(`/api/admin/orders/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});const x=await r.json();if(!r.ok){setMessage(x.error||"Status update failed");return;}if(x.invoiceId)setMessage(`Invoice ${x.invoiceId} generated automatically.`);refresh();}
  async function signout(){await fetch("/api/auth/sign-out",{method:"POST"});router.push("/admin/login");}
  function openAdd(){setSelectedProduct(null);setProductForm(emptyProduct);setProductOpen(true);}
  function openEdit(p:any){setSelectedProduct(p);setProductForm({...p,images:p.images.join(", "),features:p.features.join("\n")});setProductOpen(true);}
  async function saveProduct(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");const body={...productForm,regularPrice:Number(productForm.regularPrice),salePrice:Number(productForm.salePrice),costPrice:Number(productForm.costPrice),discount:Number(productForm.discount),stock:Number(productForm.stock),images:String(productForm.images).split(",").map((x:string)=>x.trim()).filter(Boolean),features:String(productForm.features).split("\n").map((x:string)=>x.trim()).filter(Boolean)};const url=selectedProduct?`/api/admin/products/${selectedProduct.id}`:"/api/admin/products";const r=await fetch(url,{method:selectedProduct?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const x=await r.json();setSaving(false);if(!r.ok){setMessage(x.error||"Could not save product");return;}setProductOpen(false);setMessage(selectedProduct?"Product updated successfully.":"Product added successfully.");refresh();}
  async function removeProduct(p:any){if(!confirm(`Delete ${p.name}?`))return;const r=await fetch(`/api/admin/products/${p.id}`,{method:"DELETE"});if(r.ok){setMessage("Product deleted.");refresh();}else setMessage("Could not delete product.");}

  return <main className="mx-auto max-w-7xl px-4 py-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-amber-500">Executive Command</p><h1 className="luxury mt-2 text-4xl">Admin Dashboard</h1><p className="mt-2 text-sm text-zinc-500">Live orders, invoices, products and inventory management.</p></div><button onClick={signout} className="rounded-xl border border-amber-500/20 px-4 py-2 text-sm text-amber-400">Sign Out</button></div>
    {message&&<div className="mt-5 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-sm text-amber-300">{message}</div>}

    <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[["Messages Sent","128"],["Tokens Used","45,200"],["Plan","Premium Admin Workspace"],["Gross Revenue",money(d.revenue)],["Acquisition Cost",money(d.cost)],["Net Profit/Loss",money(d.revenue-d.cost)]].map(([a,b],i)=><div key={a} className="panel rounded-2xl p-5"><p className="text-xs uppercase text-zinc-500">{a}</p><p className={`finance mt-3 text-lg ${i===5?"text-emerald-400":"text-amber-400"}`}>{b}</p></div>)}</div>

    <section className="panel mt-8 rounded-3xl p-5"><h2 className="luxury text-2xl">7-Day Performance</h2><div className="mt-6 flex h-56 items-end gap-3">{[12,18,9,24,30,15,20].map((n,i)=><div key={i} className="flex flex-1 flex-col items-center gap-2"><div className="w-full max-w-14 rounded-t-lg bg-gradient-to-t from-amber-700 to-amber-300" style={{height:`${n/30*100}%`}}/><span className="finance text-[10px] text-zinc-500">D{i+1}</span></div>)}</div></section>

    <section className="panel mt-8 rounded-3xl p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="luxury text-2xl">Product Management</h2><p className="mt-1 text-xs text-zinc-500">Add, edit, remove, quick-view and manage stock.</p></div><button onClick={openAdd} className="inline-flex items-center gap-2 rounded-xl bg-amber-500 px-4 py-2 text-sm font-bold text-black"><Plus size={16}/> Add Product</button></div><div className="mt-5 flex items-center gap-2 rounded-xl border border-white/10 bg-black px-3"><Search size={16} className="text-zinc-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products..." className="w-full bg-transparent py-3 text-sm outline-none"/></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-xs uppercase text-zinc-500"><tr><th className="p-3">Product</th><th>Price</th><th>Stock</th><th>Sold</th><th>State</th><th>Actions</th></tr></thead><tbody>{products.map((p:any)=><tr key={p.id} className="border-t border-white/5"><td className="p-3"><div className="flex items-center gap-3"><img src={p.images?.[0]} className="h-12 w-12 rounded-lg object-cover" alt=""/><div><b>{p.name}</b><div className="text-xs text-zinc-500">{p.type}</div></div></div></td><td className="finance text-amber-400">{money(p.salePrice)}</td><td><input type="number" min="0" value={p.stock} onChange={e=>{const n=Number(e.target.value);setD((x:any)=>({...x,products:x.products.map((q:any)=>q.id===p.id?{...q,stock:n}:q)}))}} onBlur={e=>stock(p.id,Number(e.target.value))} className="w-20 rounded-lg border border-white/10 bg-black px-2 py-2"/></td><td className="finance">{p.unitsSold}</td><td>{p.stock>0?<span className="text-emerald-400">Available</span>:<span className="text-red-400">Sold Out</span>}</td><td><div className="flex gap-2"><button onClick={()=>setSelectedProduct(p)} title="Quick view" className="rounded-lg border border-white/10 p-2 hover:border-amber-500/30"><Eye size={16}/></button><button onClick={()=>openEdit(p)} title="Edit" className="rounded-lg border border-white/10 p-2 hover:border-amber-500/30"><Pencil size={16}/></button><button onClick={()=>removeProduct(p)} title="Delete" className="rounded-lg border border-red-500/20 p-2 text-red-400"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div></section>

    <section className="panel mt-8 rounded-3xl p-5"><div className="flex items-center justify-between"><div><h2 className="luxury text-2xl">Orders & Invoices</h2><p className="mt-1 text-xs text-zinc-500">Every checkout is stored with customer, shipping, item and payment details.</p></div><span className="finance text-xs text-zinc-500">{d.orders.length} orders</span></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="text-xs uppercase text-zinc-500"><tr><th className="p-3">Order</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Invoice</th><th>Actions</th></tr></thead><tbody>{d.orders.map((o:any)=><tr key={o.id} className="border-t border-white/5"><td className="p-3 finance text-amber-400">{o.id}<div className="text-[10px] text-zinc-600">{new Date(o.createdAt).toLocaleString()}</div></td><td><b>{o.user?.name||o.customer}</b><div className="text-xs text-zinc-500">{o.user?.email||o.email}</div></td><td>{o.items.reduce((n:any,i:any)=>n+i.quantity,0)} item(s)</td><td className="finance">{money(o.total)}</td><td><select value={o.status} onChange={e=>status(o.id,e.target.value)} className="rounded-lg border border-amber-500/20 bg-black px-2 py-2 text-xs"><option>Pending</option><option>Confirmed</option><option>Delivered</option></select></td><td>{o.invoiceId?<a target="_blank" href={`/admin/invoices/${o.invoiceId}`} className="inline-flex items-center gap-1 text-amber-400 hover:underline"><FileText size={14}/>{o.invoiceId}</a>:<span className="text-zinc-600">Generated after confirm</span>}</td><td><button onClick={()=>setSelectedOrder(o)} className="rounded-lg border border-amber-500/20 px-3 py-2 text-xs text-amber-400">View Details</button></td></tr>)}</tbody></table></div></section>

    <div className="mt-8 grid gap-6 lg:grid-cols-2"><Inventory title="Still Available" products={d.products.filter((p:any)=>p.stock>0)} stock={stock}/><Inventory title="Sold Out" products={d.products.filter((p:any)=>p.stock===0)} stock={stock}/></div>

    {selectedOrder&&<Modal onClose={()=>setSelectedOrder(null)} title={`Order ${selectedOrder.id}`}><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-white/10 p-4"><h3 className="font-semibold text-amber-400">Customer Details</h3><p className="mt-3 text-sm">{selectedOrder.user?.name||selectedOrder.customer}</p><p className="text-sm text-zinc-400">{selectedOrder.user?.email||selectedOrder.email}</p><p className="text-sm text-zinc-400">{selectedOrder.phone||"No phone"}</p><p className="mt-3 text-sm text-zinc-300">{selectedOrder.address||"No address"}, {selectedOrder.city||""}</p></div><div className="rounded-2xl border border-white/10 p-4"><h3 className="font-semibold text-amber-400">Order Summary</h3><p className="mt-3 text-sm">Status: <b>{selectedOrder.status}</b></p><p className="text-sm">Created: {new Date(selectedOrder.createdAt).toLocaleString()}</p><p className="text-sm">Total: <b className="finance text-amber-400">{money(selectedOrder.total)}</b></p>{selectedOrder.invoiceId&&<a target="_blank" href={`/admin/invoices/${selectedOrder.invoiceId}`} className="mt-3 inline-block text-sm text-amber-400 underline">Open Invoice / PDF View</a>}</div></div><div className="mt-5 overflow-hidden rounded-2xl border border-white/10"><div className="grid grid-cols-[1fr_auto_auto] gap-3 bg-black p-3 text-xs uppercase text-zinc-500"><span>Product</span><span>Qty</span><span>Total</span></div>{selectedOrder.items.map((i:any)=><div key={i.watchId} className="grid grid-cols-[1fr_auto_auto] items-center gap-3 border-t border-white/5 p-3"><div className="flex items-center gap-3"><img src={i.productImage} className="h-12 w-12 rounded-lg object-cover" alt=""/><span>{i.productName||i.watchId}</span></div><span>{i.quantity}</span><span className="finance text-amber-400">{money(i.unitPrice*i.quantity)}</span></div>)}</div></Modal>}
    {selectedProduct&&<Modal onClose={()=>setSelectedProduct(null)} title="Product Quick View"><div className="grid gap-6 md:grid-cols-2"><img src={selectedProduct.images?.[0]} className="aspect-square w-full rounded-2xl object-cover" alt={selectedProduct.name}/><div><p className="text-xs uppercase tracking-widest text-amber-500">{selectedProduct.type}</p><h3 className="luxury mt-2 text-3xl">{selectedProduct.name}</h3><p className="finance mt-4 text-2xl text-amber-400">{money(selectedProduct.salePrice)}</p><p className="mt-4 text-sm leading-7 text-zinc-400">{selectedProduct.longDescription}</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs text-zinc-400"><span>Movement: <b className="text-white">{selectedProduct.movement}</b></span><span>Strap: <b className="text-white">{selectedProduct.strap}</b></span><span>Water: <b className="text-white">{selectedProduct.waterResistance}</b></span><span>Stock: <b className="text-white">{selectedProduct.stock}</b></span></div><div className="mt-5 flex gap-2"><button onClick={()=>{setSelectedProduct(null);openEdit(selectedProduct)}} className="rounded-xl bg-amber-500 px-4 py-2 text-sm font-bold text-black">Edit</button></div></div></div></Modal>}
    {productOpen&&<Modal onClose={()=>setProductOpen(false)} title={selectedProduct?"Edit Product":"Add New Product"}><form onSubmit={saveProduct} className="grid gap-3 md:grid-cols-2">{[["name","Product name"],["type","Category"],["regularPrice","Regular price"],["salePrice","Sale price"],["costPrice","Cost price"],["discount","Discount %"],["stock","Stock"],["movement","Movement"],["waterResistance","Water resistance"]].map(([key,label])=><input key={key} required={!['discount','costPrice'].includes(key)} value={productForm[key]} onChange={e=>setProductForm({...productForm,[key]:e.target.value})} type={['regularPrice','salePrice','costPrice','discount','stock'].includes(key)?'number':'text'} placeholder={label} className="rounded-xl border border-white/10 bg-black px-4 py-3"/>)}<select value={productForm.strap} onChange={e=>setProductForm({...productForm,strap:e.target.value})} className="rounded-xl border border-white/10 bg-black px-4 py-3"><option>Stainless Steel</option><option>Authentic Leather</option><option>Rubber</option></select><input required value={productForm.images} onChange={e=>setProductForm({...productForm,images:e.target.value})} placeholder="Image URLs, comma separated" className="md:col-span-2 rounded-xl border border-white/10 bg-black px-4 py-3"/><textarea value={productForm.features} onChange={e=>setProductForm({...productForm,features:e.target.value})} placeholder="Features, one per line" rows={4} className="md:col-span-2 rounded-xl border border-white/10 bg-black px-4 py-3"/><textarea value={productForm.longDescription} onChange={e=>setProductForm({...productForm,longDescription:e.target.value})} placeholder="Long description" rows={4} className="md:col-span-2 rounded-xl border border-white/10 bg-black px-4 py-3"/><button disabled={saving} className="md:col-span-2 rounded-xl bg-amber-500 py-3 font-bold text-black">{saving?"Saving...":selectedProduct?"Save Changes":"Add Product"}</button></form></Modal>}
  </main>
}

function Modal({children,onClose,title}:{children:React.ReactNode;onClose:()=>void;title:string}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-4xl overflow-auto rounded-3xl border border-amber-500/20 bg-[#0d0d0d] p-6 shadow-2xl"><div className="flex items-center justify-between gap-4"><h2 className="luxury text-2xl">{title}</h2><button onClick={onClose} className="rounded-full p-2 text-zinc-400 hover:text-amber-400"><X/></button></div><div className="mt-6">{children}</div></div></div>}
function Inventory({title,products,stock}:{title:string;products:any[];stock:(id:string,s:number)=>void}){const[v,setV]=useState<Record<string,number>>({});return <section className="panel rounded-3xl p-5"><div className="flex justify-between"><h2 className="luxury text-2xl">{title}</h2><span className="finance text-xs text-zinc-500">{products.length}</span></div><div className="mt-5 space-y-3">{products.map(p=><div key={p.id} className="flex items-center gap-3 rounded-xl bg-black p-3"><img src={p.images[0]} className="h-12 w-12 rounded-lg object-cover" alt=""/><span className="flex-1 text-sm">{p.name}</span><input type="number" min="0" value={v[p.id]??p.stock} onChange={e=>setV({...v,[p.id]:Number(e.target.value)})} className="w-20 rounded-lg border border-white/10 bg-zinc-950 px-2 py-2 text-xs"/><button onClick={()=>stock(p.id,v[p.id]??p.stock)} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-black">Save</button></div>)}</div></section>}
