"use client";

import { useEffect, useMemo, useState } from "react";
import { Eye, FileText, ImagePlus, LogOut, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { money } from "@/lib/format";

type Product = any;
type Order = any;
const emptyProduct = { name:"", type:"Men's Watches", regularPrice:0, salePrice:0, costPrice:0, discount:0, stock:0, images:"", features:"", longDescription:"", movement:"Japanese Quartz", strap:"Stainless Steel", waterResistance:"30M" };

export default function AdminClient({ initial }: { initial: any }) {
  const [d, setD] = useState(initial);
  const [search, setSearch] = useState("");
  const [tab, setTab] = useState<"overview"|"products"|"orders">("overview");
  const [selectedOrder, setSelectedOrder] = useState<Order|null>(null);
  const [selectedProduct, setSelectedProduct] = useState<Product|null>(null);
  const [productForm, setProductForm] = useState<any>(emptyProduct);
  const [productOpen, setProductOpen] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState("");
  const [uploading, setUploading] = useState(false);
  const router = useRouter();

  useEffect(() => { setD(initial); }, [initial]);

  const products = useMemo(() => d.products.filter((p:any) => `${p.name} ${p.type}`.toLowerCase().includes(search.toLowerCase())), [d.products, search]);
  const revenue = Number(d.revenue || 0);
  const cost = Number(d.cost || 0);
  const inventoryValue = d.products.reduce((sum:number, p:any) => sum + p.stock * p.costPrice, 0);

  const refresh = () => router.refresh();
  async function stock(id:string, value:number) { const r = await fetch(`/api/admin/products/${id}`, { method:"PATCH", headers:{"Content-Type":"application/json"}, body:JSON.stringify({stock:Math.max(0, Math.floor(value))}) }); if (!r.ok) setMessage("Stock update failed."); else refresh(); }
  async function status(id:string, value:string) { const r = await fetch(`/api/admin/orders/${id}`, { method:"PATCH", headers:{"Content-Type":"application/json"}, body:JSON.stringify({status:value}) }); const x = await r.json(); if (!r.ok) setMessage(x.error || "Status update failed."); else { setMessage(x.invoiceId ? `Invoice ${x.invoiceId} is ready.` : "Order updated."); refresh(); } }
  async function signout() { await fetch("/api/auth/sign-out", { method:"POST" }); router.replace("/admin/login"); router.refresh(); }
  function openAdd() { setSelectedProduct(null); setProductForm(emptyProduct); setProductOpen(true); }
  function openEdit(p:any) { setSelectedProduct(p); setProductForm({...p, images:p.images.join(", "), features:p.features.join("\n")}); setProductOpen(true); }
  async function saveProduct(e:React.FormEvent) {
    e.preventDefault(); setSaving(true); setMessage("");
    const body = {...productForm, regularPrice:Number(productForm.regularPrice), salePrice:Number(productForm.salePrice), costPrice:Number(productForm.costPrice), discount:Number(productForm.discount), stock:Number(productForm.stock), images:String(productForm.images).split(",").map((x:string)=>x.trim()).filter(Boolean), features:String(productForm.features).split("\n").map((x:string)=>x.trim()).filter(Boolean)};
    const url = selectedProduct ? `/api/admin/products/${selectedProduct.id}` : "/api/admin/products";
    const r = await fetch(url, { method:selectedProduct?"PATCH":"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify(body) });
    const x = await r.json(); setSaving(false); if (!r.ok) return setMessage(x.error || "Could not save product."); setProductOpen(false); setMessage(selectedProduct ? "Product updated." : "Product added."); refresh();
  }
  async function removeProduct(p:any) { if (!confirm(`Remove ${p.name} from the storefront?`)) return; const r = await fetch(`/api/admin/products/${p.id}`, { method:"DELETE" }); setMessage(r.ok ? "Product removed from storefront." : "Could not remove product."); if (r.ok) refresh(); }
  async function uploadImages(files:FileList|null) {
    if (!files?.length) return; setUploading(true); const form = new FormData(); Array.from(files).slice(0,8).forEach(f => form.append("images", f));
    const r = await fetch("/api/admin/upload", { method:"POST", body:form }); const x = await r.json(); setUploading(false); if (!r.ok) return setMessage(x.error || "Upload failed."); setProductForm((v:any)=>({...v, images:[v.images, ...x.urls].filter(Boolean).join(", ")})); setMessage(`${x.urls.length} image(s) uploaded.`);
  }

  return <main className="admin-shell mx-auto max-w-[1400px] px-4 py-10 md:px-6">
    <header className="text-center"><p className="text-[10px] uppercase tracking-[.3em] text-amber-500">Novis Management Studio</p><h1 className="luxury mt-3 text-4xl md:text-5xl">Store administration</h1><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-zinc-500">Products, stock, orders, invoices and storefront operations in one controlled workspace.</p><button onClick={signout} className="mt-5 inline-flex items-center gap-2 rounded-full border border-amber-500/20 px-4 py-2 text-xs text-amber-400"><LogOut size={14}/> Sign out</button></header>
    {message && <div className="mx-auto mt-6 max-w-3xl rounded-xl border border-amber-500/20 bg-amber-500/5 p-3 text-center text-sm text-amber-300">{message}</div>}

    <nav className="mx-auto mt-10 flex max-w-2xl justify-center gap-2 rounded-2xl border border-white/10 bg-[#0a0a0a] p-2">{(["overview","products","orders"] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`flex-1 rounded-xl px-3 py-3 text-[10px] uppercase tracking-[.14em] ${tab===t?"bg-amber-500 font-bold text-black":"text-zinc-500 hover:text-amber-400"}`}>{t}</button>)}</nav>

    {tab === "overview" && <>
      <section className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Revenue",money(revenue)],["Cost",money(cost)],["Gross margin",money(revenue-cost)],["Inventory at cost",money(inventoryValue)]].map(([label,value],i)=><div key={label} className="rounded-2xl border border-white/10 bg-[#0c0c0c] p-5"><p className="text-[9px] uppercase tracking-[.16em] text-zinc-600">{label}</p><p className={`finance mt-3 text-xl ${i===2?"text-emerald-400":"text-amber-400"}`}>{value}</p></div>)}</section>
      <section className="mt-8 grid gap-5 lg:grid-cols-3"><div className="lg:col-span-2 rounded-3xl border border-white/10 bg-[#0c0c0c] p-6"><div className="flex items-center justify-between"><div><p className="text-[9px] uppercase tracking-widest text-amber-500">Recent activity</p><h2 className="luxury mt-2 text-2xl">Latest orders</h2></div><button onClick={()=>setTab("orders")} className="text-xs text-amber-400">View all</button></div><div className="mt-5 space-y-2">{d.orders.slice(0,5).map((o:any)=><button key={o.id} onClick={()=>setSelectedOrder(o)} className="flex w-full items-center gap-4 border-b border-white/5 py-4 text-left"><span className="finance text-xs text-amber-400">{o.id}</span><span className="flex-1"><b className="text-sm">{o.user?.name||o.customer}</b><small className="ml-2 text-zinc-600">{o.items?.reduce((n:number,i:any)=>n+i.quantity,0)} item(s)</small></span><span className="finance text-xs">{money(o.total)}</span><span className="text-[10px] text-zinc-500">{o.status}</span></button>)}{!d.orders.length&&<p className="py-8 text-center text-sm text-zinc-600">No orders yet.</p>}</div></div><div className="rounded-3xl border border-amber-500/15 bg-[#0c0c0c] p-6"><p className="text-[9px] uppercase tracking-widest text-amber-500">Catalog health</p><h2 className="luxury mt-2 text-2xl">Inventory</h2><div className="mt-6 space-y-5"><Metric label="Products" value={d.products.length}/><Metric label="Available" value={d.products.filter((p:any)=>p.stock>0).length}/><Metric label="Sold out" value={d.products.filter((p:any)=>p.stock===0).length}/><Metric label="Units sold" value={d.products.reduce((n:number,p:any)=>n+p.unitsSold,0)}/></div></div></section>
    </>}

    {tab === "products" && <ProductPanel products={products} search={search} setSearch={setSearch} openAdd={openAdd} openEdit={openEdit} removeProduct={removeProduct} stock={stock} setSelectedProduct={setSelectedProduct}/>} 
    {tab === "orders" && <OrderPanel orders={d.orders} status={status} setSelectedOrder={setSelectedOrder}/>} 

    {selectedOrder && <Modal onClose={()=>setSelectedOrder(null)} title={`Order ${selectedOrder.id}`}><div className="grid gap-5 md:grid-cols-2"><div className="rounded-2xl border border-white/10 p-5"><p className="text-[9px] uppercase tracking-widest text-amber-500">Customer</p><h3 className="mt-2 text-lg">{selectedOrder.user?.name||selectedOrder.customer}</h3><p className="text-sm text-zinc-500">{selectedOrder.user?.email||selectedOrder.email}</p><p className="mt-3 text-sm text-zinc-400">{selectedOrder.phone||"No phone"}</p><p className="mt-2 text-sm text-zinc-400">{selectedOrder.address||"No address"}{selectedOrder.city?`, ${selectedOrder.city}`:""}</p></div><div className="rounded-2xl border border-white/10 p-5"><p className="text-[9px] uppercase tracking-widest text-amber-500">Order</p><p className="mt-2 text-sm">Status: <b>{selectedOrder.status}</b></p><p className="mt-2 text-sm">Total: <b className="finance text-amber-400">{money(selectedOrder.total)}</b></p>{selectedOrder.invoiceId&&<a target="_blank" rel="noreferrer" href={`/admin/invoices/${selectedOrder.invoiceId}`} className="mt-4 inline-flex items-center gap-2 text-xs text-amber-400"><FileText size={14}/> Open invoice</a>}</div></div><div className="mt-5 space-y-2">{selectedOrder.items?.map((i:any)=><div key={i.watchId} className="flex items-center gap-3 rounded-xl border border-white/5 bg-black p-3"><img src={i.productImage} className="h-12 w-12 rounded-lg object-cover" alt=""/><span className="flex-1 text-sm">{i.productName||i.watchId} × {i.quantity}</span><span className="finance text-amber-400">{money(i.unitPrice*i.quantity)}</span></div>)}</div></Modal>}
    {selectedProduct && !productOpen && <Modal onClose={()=>setSelectedProduct(null)} title="Product preview"><div className="grid gap-6 md:grid-cols-2"><img src={selectedProduct.images?.[0]} className="aspect-square w-full object-cover" alt={selectedProduct.name}/><div><p className="eyebrow">{selectedProduct.type}</p><h3 className="luxury mt-2 text-3xl">{selectedProduct.name}</h3><p className="finance mt-4 text-xl text-amber-400">{money(selectedProduct.salePrice)}</p><p className="mt-4 text-sm leading-7 text-zinc-400">{selectedProduct.longDescription}</p><div className="mt-5 grid grid-cols-2 gap-3 text-xs text-zinc-500"><span>Movement<br/><b className="text-white">{selectedProduct.movement}</b></span><span>Strap<br/><b className="text-white">{selectedProduct.strap}</b></span><span>Water<br/><b className="text-white">{selectedProduct.waterResistance}</b></span><span>Stock<br/><b className="text-white">{selectedProduct.stock}</b></span></div><button onClick={()=>openEdit(selectedProduct)} className="gold-button mt-6">Edit Product</button></div></div></Modal>}
    {productOpen && <Modal onClose={()=>setProductOpen(false)} title={selectedProduct?"Edit product":"Add product"}><form onSubmit={saveProduct} className="grid gap-3 md:grid-cols-2">{[["name","Product name"],["type","Category"],["regularPrice","Regular price"],["salePrice","Sale price"],["costPrice","Cost price"],["discount","Discount %"],["stock","Stock"],["movement","Movement"],["waterResistance","Water resistance"]].map(([key,label])=><input key={key} required={!['discount','costPrice'].includes(key)} value={productForm[key]} onChange={e=>setProductForm({...productForm,[key]:e.target.value})} type={['regularPrice','salePrice','costPrice','discount','stock'].includes(key)?'number':'text'} placeholder={label} className="rounded-xl border border-white/10 bg-black px-4 py-3"/>)}<select value={productForm.strap} onChange={e=>setProductForm({...productForm,strap:e.target.value})} className="rounded-xl border border-white/10 bg-black px-4 py-3"><option>Stainless Steel</option><option>Authentic Leather</option><option>Rubber</option></select><div className="md:col-span-2 flex flex-wrap items-center gap-2"><input value={productForm.images} onChange={e=>setProductForm({...productForm,images:e.target.value})} placeholder="Image URLs, comma separated" className="min-w-0 flex-1 rounded-xl border border-white/10 bg-black px-4 py-3"/><label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-amber-500/20 px-4 py-3 text-xs text-amber-400"><ImagePlus size={15}/>{uploading?"Uploading...":"Upload images"}<input type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden onChange={e=>uploadImages(e.target.files)}/></label></div><textarea value={productForm.features} onChange={e=>setProductForm({...productForm,features:e.target.value})} placeholder="Features, one per line" rows={4} className="md:col-span-2 rounded-xl border border-white/10 bg-black px-4 py-3"/><textarea value={productForm.longDescription} onChange={e=>setProductForm({...productForm,longDescription:e.target.value})} placeholder="Product description" rows={4} className="md:col-span-2 rounded-xl border border-white/10 bg-black px-4 py-3"/><button disabled={saving} className="md:col-span-2 rounded-xl bg-amber-500 py-3 font-bold text-black">{saving?"Saving...":selectedProduct?"Save Changes":"Create Product"}</button></form></Modal>}
  </main>;
}

function StatusControl({order,onChange}:{order:any;onChange:(id:string,status:string)=>void}){
  const next:Record<string,string|null>={Pending:"Confirmed",Confirmed:"Out for Delivery","Out for Delivery":"Delivered",Delivered:"Return",Return:null};
  const target=next[order.status]??null;
  if(!target) return <span className="rounded-lg border border-white/10 px-3 py-2 text-[10px] uppercase tracking-wider text-zinc-500">Final status</span>;
  return <select value={order.status} onChange={e=>e.target.value!==order.status&&onChange(order.id,e.target.value)} className="rounded-lg border border-amber-500/20 bg-black px-3 py-2 text-xs">
    <option value={order.status}>{order.status}</option>
    <option value={target}>{target}</option>
  </select>;
}

function Metric({label,value}:{label:string;value:number}){return <div className="flex items-end justify-between border-b border-white/5 pb-3"><span className="text-xs text-zinc-500">{label}</span><strong className="finance text-amber-400">{value.toLocaleString()}</strong></div>}
function ProductPanel({products,search,setSearch,openAdd,openEdit,removeProduct,stock,setSelectedProduct}:{products:any[];search:string;setSearch:(v:string)=>void;openAdd:()=>void;openEdit:(p:any)=>void;removeProduct:(p:any)=>void;stock:(id:string,n:number)=>void;setSelectedProduct:(p:any)=>void}){return <section className="mt-8 rounded-3xl border border-white/10 bg-[#0c0c0c] p-5 md:p-7"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[9px] uppercase tracking-widest text-amber-500">Catalog</p><h2 className="luxury mt-2 text-3xl">Product management</h2></div><button onClick={openAdd} className="gold-button"><Plus size={15}/> Add product</button></div><div className="mt-6 flex items-center gap-2 rounded-xl border border-white/10 bg-black px-3"><Search size={16} className="text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by product or category" className="w-full border-0 bg-transparent"/></div><div className="mt-5 space-y-2">{products.map((p:any)=><div key={p.id} className="grid gap-3 rounded-2xl border border-white/5 bg-black p-3 sm:grid-cols-[1fr_auto_auto_auto] sm:items-center"><div className="flex items-center gap-3"><img src={p.images?.[0]} className="h-14 w-14 rounded-xl object-cover" alt=""/><div><b className="text-sm">{p.name}</b><p className="text-[10px] text-zinc-600">{p.type}</p></div></div><span className="finance text-sm text-amber-400">{money(p.salePrice)}</span><input type="number" min="0" value={p.stock} onChange={e=>stock(p.id,Number(e.target.value))} className="w-full rounded-lg border border-white/10 bg-[#0b0b0b] px-3 py-2 text-xs sm:w-20"/><div className="flex gap-1"><button onClick={()=>setSelectedProduct(p)} className="rounded-lg border border-white/10 p-2 text-zinc-400 hover:text-amber-400"><Eye size={15}/></button><button onClick={()=>openEdit(p)} className="rounded-lg border border-white/10 p-2 text-zinc-400 hover:text-amber-400"><Pencil size={15}/></button><button onClick={()=>removeProduct(p)} className="rounded-lg border border-red-500/15 p-2 text-red-400"><Trash2 size={15}/></button></div></div>)}{!products.length&&<p className="py-10 text-center text-sm text-zinc-600">No products match the search.</p>}</div></section>}
function OrderPanel({orders,status,setSelectedOrder}:{orders:any[];status:(id:string,s:string)=>void;setSelectedOrder:(o:any)=>void}){return <section className="mt-8 rounded-3xl border border-white/10 bg-[#0c0c0c] p-5 md:p-7"><p className="text-[9px] uppercase tracking-widest text-amber-500">Sales</p><h2 className="luxury mt-2 text-3xl">Orders & invoices</h2><div className="mt-6 space-y-2">{orders.map((o:any)=><div key={o.id} className="grid gap-3 rounded-2xl border border-white/5 bg-black p-4 md:grid-cols-[1.1fr_1fr_auto_auto_auto] md:items-center"><div><b className="finance text-xs text-amber-400">{o.id}</b><p className="text-sm">{o.user?.name||o.customer}</p></div><div className="text-xs text-zinc-500">{o.items?.reduce((n:number,i:any)=>n+i.quantity,0)} item(s)<br/>{o.user?.email||o.email}</div><strong className="finance text-sm">{money(o.total)}</strong><StatusControl order={o} onChange={status} /><button onClick={()=>setSelectedOrder(o)} className="rounded-lg border border-amber-500/20 px-3 py-2 text-xs text-amber-400">View</button></div>)}{!orders.length&&<p className="py-10 text-center text-sm text-zinc-600">No orders yet.</p>}</div></section>}
function Modal({children,onClose,title}:{children:React.ReactNode;onClose:()=>void;title:string}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/85 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-5xl overflow-auto rounded-3xl border border-amber-500/20 bg-[#0d0d0d] p-6 shadow-2xl"><div className="flex items-center justify-between gap-4"><h2 className="luxury text-2xl">{title}</h2><button onClick={onClose} className="rounded-full p-2 text-zinc-400 hover:text-amber-400"><X/></button></div><div className="mt-6">{children}</div></div></div>}
