import { db } from "@/lib/db";
import { money } from "@/lib/format";
import { requireRole } from "@/lib/auth";
import { notFound, redirect } from "next/navigation";
import Link from "next/link";

export default async function InvoicePage({params}:{params:{id:string}}){
  const s=await requireRole("ADMIN"); if(!s) redirect("/admin/login");
  const orders:any[]=await db.order.findMany({});
  const order:any=orders.find(o=>o.invoiceId===params.id);
  if(!order) notFound();
  return <main className="mx-auto max-w-4xl px-4 py-10 print:bg-white print:text-black"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-amber-500">Sveston Luxury AI Suite</p><h1 className="luxury mt-2 text-4xl">Invoice</h1><p className="mt-2 finance text-amber-400">{order.invoiceId}</p></div><div className="flex gap-3"><Link href={`/api/admin/invoices/${order.invoiceId}/pdf`} target="_blank" className="rounded-xl bg-amber-500 px-4 py-2 font-bold text-black">View PDF</Link></div></div><div className="mt-8 grid gap-5 md:grid-cols-2"><div className="panel rounded-2xl p-5"><h2 className="font-semibold text-amber-400">Bill To</h2><p className="mt-3">{order.customer}</p><p className="text-sm text-zinc-400">{order.email}</p><p className="text-sm text-zinc-400">{order.phone||"—"}</p><p className="mt-2 text-sm text-zinc-300">{order.address||"—"}, {order.city||"—"}</p></div><div className="panel rounded-2xl p-5"><h2 className="font-semibold text-amber-400">Order</h2><p className="mt-3">Order ID: <span className="finance">{order.id}</span></p><p className="text-sm">Date: {new Date(order.createdAt).toLocaleString()}</p><p className="text-sm">Status: {order.status}</p><p className="text-sm">Payment: Cash on Delivery</p></div></div><div className="panel mt-6 overflow-hidden rounded-2xl"><table className="w-full text-left text-sm"><thead className="bg-black/40 text-xs uppercase text-zinc-500"><tr><th className="p-4">Product</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr></thead><tbody>{order.items.map((i:any)=><tr key={i.watchId} className="border-t border-white/5"><td className="p-4"><div className="flex items-center gap-3">{i.productImage&&<img src={i.productImage} className="h-12 w-12 rounded-lg object-cover" alt=""/>}<span>{i.productName||i.watchId}</span></div></td><td>{i.quantity}</td><td className="finance">{money(i.unitPrice)}</td><td className="finance text-amber-400">{money(i.unitPrice*i.quantity)}</td></tr>)}</tbody><tfoot><tr className="border-t border-white/10"><td colSpan={3} className="p-4 text-right font-bold">Grand Total</td><td className="finance p-4 text-lg font-bold text-amber-400">{money(order.total)}</td></tr></tfoot></table></div><p className="mt-6 text-center text-xs text-zinc-600">Generated when the order was confirmed.</p></main>
}
