"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useStore } from "@/components/StoreProvider";
import { money } from "@/lib/format";

export default function Checkout(){
  const {cart,clearCart}=useStore(); const [products,setProducts]=useState<any[]>([]); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const router=useRouter();
  const [v,setV]=useState({name:"",email:"",address:"",city:"",phone:""});
  useEffect(()=>{fetch("/api/products").then(r=>r.json()).then(setProducts).catch(()=>setError("Could not load the current catalog."));},[]);
  const rows=cart.map(i=>({i,p:products.find(x=>x.id===i.id)})).filter(x=>x.p); const subtotal=rows.reduce((s,x)=>s+x.p.salePrice*x.i.quantity,0); const delivery=subtotal>=10000||!subtotal?0:250; const total=subtotal+delivery;
  async function submit(e:React.FormEvent){e.preventDefault();if(!rows.length)return setError("Your cart is empty.");setLoading(true);setError("");try{const res=await fetch("/api/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer:v,items:cart})});const d=await res.json();if(!res.ok){setError(d.error||"Could not create order.");setLoading(false);return;}clearCart();router.push(`/order-success?id=${d.id}`);}catch{setError("Network error. Please try again.");setLoading(false);}}
  return <main className="page-shell"><div className="mb-10 text-center"><p className="eyebrow">Secure checkout</p><h1 className="luxury mt-3 text-5xl">Complete your order</h1><p className="mx-auto mt-3 max-w-xl text-sm text-zinc-500">Cash on delivery is currently available. Stock is verified again when the order is submitted.</p></div><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><form onSubmit={submit} className="panel rounded-3xl p-6 md:p-8"><div className="grid gap-4 sm:grid-cols-2"><input required placeholder="Full name" value={v.name} onChange={e=>setV({...v,name:e.target.value})}/><input required type="email" placeholder="Email address" value={v.email} onChange={e=>setV({...v,email:e.target.value})}/><input required placeholder="Phone number" value={v.phone} onChange={e=>setV({...v,phone:e.target.value})}/><input required placeholder="City" value={v.city} onChange={e=>setV({...v,city:e.target.value})}/></div><textarea required rows={5} placeholder="Complete shipping address" value={v.address} onChange={e=>setV({...v,address:e.target.value})} className="mt-4 w-full"/>{error&&<p className="mt-4 text-sm text-red-400">{error}</p>}<button disabled={loading||!rows.length} className="gold-button mt-5 w-full">{loading?"Placing order...":"Place cash-on-delivery order"}</button></form><aside className="panel h-fit rounded-3xl p-6"><p className="eyebrow">Your selection</p><h2 className="luxury mt-2 text-2xl">Order summary</h2><div className="mt-5 space-y-4">{rows.map(x=><div key={x.p.id} className="flex gap-3"><img src={x.p.images[0]} className="h-16 w-14 rounded-lg object-cover" alt=""/><div className="flex-1"><p className="text-sm">{x.p.name}</p><p className="text-xs text-zinc-600">Qty {x.i.quantity}</p></div><span className="finance text-xs text-amber-400">{money(x.p.salePrice*x.i.quantity)}</span></div>)}<div className="border-t border-white/10 pt-4 text-sm"><div className="flex justify-between"><span className="text-zinc-500">Subtotal</span><span>{money(subtotal)}</span></div><div className="mt-2 flex justify-between"><span className="text-zinc-500">Delivery</span><span>{delivery?money(delivery):"FREE"}</span></div><div className="mt-3 flex justify-between text-base"><strong>Total</strong><strong className="finance text-amber-400">{money(total)}</strong></div></div></div></aside></div></main>;
}
